version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Running pre build commands"
      - npm install -g serverless
    commands:.
      - echo "Running build commands"
      - npm ci
  post_build: 
    commands:
      - echo "Running post build commands"
      - sls deploy --verbose --stage $STAGE       